### ISSUE TITLE
Phone number support for verification of credential

### ISSUE THREAD

**Issue by dimakuba** [bulktrade/SMSBOX#8]

**Comment by HVND** [comment]
User can use the telephone number or email address to login.

https://github.com/bulktrade/SMSBOX/commit/a1350db2bf9f5bcbeec5285079658bf34c23d91b

**Comment by dimakuba** [comment]
User can use the telephone number or email address to login (https://github.com/bulktrade/SMSBOX/commit/a1350db2bf9f5bcbeec5285079658bf34c23d91b)
